sudo: required
services:
  - docker

before_install:
  - docker image build -t crileroro/docker-kubernetes -f Dockerfile.dev .

script:
  - docker container run -e CI=true crileroro/docker-kubernetes npm run test

