sudo: required
services:
  - docker

before_install:
  - docker image build -t crileroro/docker-kubernetes -f Dockerfile.dev .

script:
  - docker container run -e CI=true crileroro/docker-kubernetes npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-522410467679"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY

