version: '3.7'
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: 'node-frontend'
    ports:
      - '3000:3000'
    volumes:
      - ".:/app"
      - "/app/node_modules"

  web-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app"
      - "/app/node_modules"
    command: ["npm", "run", "test"]